apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage
provisioner: kmaster.besanket.com
parameters:
  server: kmaster.besanket.com 
  path: /opt/data
  readOnly: "false"
